"""empty message

Revision ID: 8aad0d8ccc66
Revises: a16ad28f9525
Create Date: 2020-01-14 15:30:29.941783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aad0d8ccc66'
down_revision = 'a16ad28f9525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
