"""empty message

Revision ID: 9d445c5c1a96
Revises: f9a73f3cd47a
Create Date: 2020-01-14 15:06:01.416616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d445c5c1a96'
down_revision = 'f9a73f3cd47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', sa.String(length=32), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'categories')
    # ### end Alembic commands ###
