"""empty message

Revision ID: debc8ce2c458
Revises: 9d445c5c1a96
Create Date: 2020-01-14 15:09:32.037968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debc8ce2c458'
down_revision = '9d445c5c1a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
